definitions:
  utils.Payload:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/v1/files:
    get:
      description: List all uploaded files with their download links
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Payload'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Payload'
      summary: List all uploaded files
      tags:
      - Files
  /api/v1/files/download/{id}:
    get:
      description: Download a file by its ID
      parameters:
      - description: File ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Payload'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Payload'
      summary: Download a file
      tags:
      - Files
  /api/v1/files/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload files and get their unique download links
      parameters:
      - description: Files to upload
        in: formData
        name: files
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Payload'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Payload'
      summary: Upload one or more files
      tags:
      - Files
swagger: "2.0"
